### ISSUE TITLE
agent refuses to start when network_mode is host

### ISSUE THREAD

**Issue by Smartype** [portainer/agent#105]
Run the Portainer Agent in host network mode. It fails to start. Checking the code found that it tries to get it's container IP address from container hostname, when it fail to get the IP, it quits.

Question, is it the expected behaviours?  I am not a guru on Portainer agent so I do not if it's possible to work in host network mode.

```
[root@localhost portainer-agent]# docker-compose up
Recreating portainer_agent ... done
Attaching to portainer_agent
portainer_agent    | 2019/12/23 15:16:55 [DEBUG] [main,configuration] [Member tags: map[AgentPort:9001 EngineStatus:standalone NodeName:localhost.localdomain]]
portainer_agent    | 2019/12/23 15:16:55 [ERROR] [main,docker] [message: Unable to retrieve local agent IP address] [error: Error: No such container: localhost.localdomain]
portainer_agent exited with code 1
```

**Comment by Smartype** [comment]
Here is compose file:

```
version: '3'

services:

        portainer_agent:
                image: 'portainer/agent'

                container_name: 'portainer_agent'

                network_mode: host

                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - /var/lib/docker/volumes:/var/lib/docker/volumes
                        - /:/host
                        - ./data:/data

                environment:
                        - EDGE_INSECURE_POLL=1
                        - EDGE=1
                        - EDGE_ID=XX
                        - EDGE_KEY=XX
                        - CAP_HOST_MANAGEMENT=1
                        - LOG_LEVEL=debug

```
