### ISSUE TITLE
Error when running on a Synology NAS Docker

### ISSUE THREAD

**Issue by miracl-cutelemon173** [portainer/agent#188]
I was trying to launch Portainer Agent latest ona synology nas docker but i got this error:
[ERROR] [main,docker] [message: Unable to retrieve information from Docker] [error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Any solutions?

**Comment by MadsBen** [comment]
Old issue, but this is my compose-file for agent on Synology.

```
  agent:
    image: portainer/agent
    container_name: portainer_agent
    environment:
      AGENT_PORT: 9001
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/@docker/volumes:/var/lib/docker/volumes
    restart: always
```
Replace "volume1" with whatever volume your Synology docker app is installed on. 
You can locate the folder with this command:
`echo "$(sudo docker info --format '{{.DockerRootDir}}')/volumes"
`
