### ISSUE TITLE
Agent wont start after update "Unable to retrieve local agent IP address"

### ISSUE THREAD

**Issue by Trufax** [portainer/agent#203]
Hello,

i use watchtower to update my containers but the Portainer agent keeps to have issues when updated. 
Whenever watchtower updates the container, it keeps restarting with the following error message:

`
agent_1       | 2021/08/05 12:22:25 [ERROR] [main,docker] [message: Unable to retrieve local agent IP address] [error: Error: No such container: 6c9fd4504fb5]
`

And i use the following compose file:

```
portainer:
    image: portainer/portainer-ce
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    restart: unless-stopped
      
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: portainer_agent_1 portainer_watchtower_1
    restart: unless-stopped
```

I can fix it by manually running docker-compose down and than up again but this defeats the whole purpose of the automatic updates. 

Regards
