### ISSUE TITLE
Portainer agents enter restarting state after a few minutes

### ISSUE THREAD

**Issue by staxfur** [portainer/agent#268]
Hello,
I'm facing the issue that when I start a portainer agend, it's starting fine and runs well. I even can connect with my portainer server (CE) normally without any issue. The problem appears after a few hours. Basically the container suddenly has the status `restarting` as shown below:
![image](https://user-images.githubusercontent.com/39553804/157380399-45d2e05a-227e-4b89-90fc-b02bc621490c.png)

The logs:
```
2022/03/09 05:47:13 [INFO] [main] [message: Agent running on Docker platform]
2022/03/09 05:47:13 [ERROR] [main,docker] [message: Unable to retrieve local agent IP address] [error: Error: No such container: e48af7393b76]
2022/03/09 05:48:14 [INFO] [main] [message: Agent running on Docker platform]
2022/03/09 05:48:14 [ERROR] [main,docker] [message: Unable to retrieve local agent IP address] [error: Error: No such container: e48af7393b76]
2022/03/09 05:49:14 [INFO] [main] [message: Agent running on Docker platform]
2022/03/09 05:49:14 [ERROR] [main,docker] [message: Unable to retrieve local agent IP address] [error: Error: No such container: e48af7393b76]
```

portainer version: 2.11.1 (the one standing in the webui on the lower left)
other version: 20.10.12
![image](https://user-images.githubusercontent.com/39553804/157380971-4325786e-d3d9-436d-9611-5a087ffe0de8.png)

I'm using the newest docker container and run it using docker compose. There is no problem with the portainer server. The other containers are running fine and the problem occurs on all of my 3 portainer-agent nodes.

The docker compose:
```yml
version: "3"

services:
  step-ca:
    image: docker.io/smallstep/step-ca
    container_name: step-ca
    restart: unless-stopped
    ports: 
      - 10.10.11.20:443:443
    volumes:
      - step:/home/step
    labels:
      - com.centurylinklabs.watchtower.enable=true
  watchtower:
    image: docker.io/containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - NO_COLOR=true
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_TIMEOUT=300s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  portainer-agent:
    image: cr.portainer.io/portainer/agent
    container_name: portainer-agent
    restart: unless-stopped
    environment:
      - AGENT_SECRET=${AGENT_SECRET}
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  step:
    external: true
```

I hope you can give me some assistance in fixing this problem. Thank you really much!
