### ISSUE TITLE
Allow the agent probe timeout and interval to be set

### ISSUE THREAD

**Issue by huib-portainer** [portainer/agent#293]
Allow the agent probe timeout and interval to be set to improve instability issues of the agent within a Swarm cluster.

Optionally provide the environment variables to the agent:
`AGENT_CLUSTER_PROBE_TIMEOUT` which has a default value of `500ms`
`AGENT_CLUSTER_PROBE_INTERVAL` which has a default value of `1s`

These parameters should only be overriden when experiencing agent cluster instability
Default values should work in most clustering use cases but some cluster/network topologies might cause the agent cluster to be unstable and seeing a lot of agent join/leave cluster events.
There is no recommended value/range to be set here and instead it is recommended to experiment with different values if facing instability issues.

Example `agent-develop-stack.yml`
```
version: '3.2'
services:
  agent-develop:
    image: portainerci/agent:develop
    environment:
      AGENT_CLUSTER_PROBE_TIMEOUT: 500ms
      AGENT_CLUSTER_PROBE_INTERVAL: 1s
      LOG_LEVEL: DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
networks:
  portainer_agent:
    driver: overlay
    attachable: true
```

Which can be used as follows
```
docker stack deploy --compose-file=agent-develop-stack.yml portainer-agent
```
