### ISSUE TITLE
Edge agent didn't start on manager

### ISSUE THREAD

**Issue by rajabiy** [portainer/agent#455]
I have using docker swarm for portainer deployment

```
version: '3.2'

services:
  agent:
    image: portainer/agent:2.17.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

        
  portainer:
    image: portainer/portainer-ee:2.17.1-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      #- "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
```

after deployment i get this error on manager node

```
docker container logs 12c54558ea09
2023/03/30 09:35AM INF github.com/portainer/agent/cmd/agent/main.go:83 > agent running on Docker platform |
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb4a0ed]

goroutine 1 [running]:
github.com/portainer/agent/docker.getSwarmConfiguration(_, {{0xc00016f300, 0x3b}, 0xb, 0x5, 0x0, 0x6, 0x9, {0xc00016a1c0, 0x8}, ...}, ...)
	github.com/portainer/agent/docker/docker.go:183 +0xed
github.com/portainer/agent/docker.(*InfoService).GetRuntimeConfigurationFromDockerEngine(0xc000479800?)
	github.com/portainer/agent/docker/docker.go:52 +0x225
main.main()
	github.com/portainer/agent/cmd/agent/main.go:87 +0x333
```
