### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by deadbeef84** [portainer/agent#90]
We're having trouble with the portainer agent memory increasing continously, here's a graph of a 2 node swarm:
![image](https://user-images.githubusercontent.com/961178/66115969-36651d80-e5d2-11e9-813f-2e05fa84c679.png)

As you can see from the screenshot one of the agents gets killed by the OOM after reaching 100% (128MB). The memory usage of the other agent then drop.

Here are logs from the agent around the time where it gets killed (chonologically reversed, sorry):
![10 0 1 21_5601_app_kibana](https://user-images.githubusercontent.com/961178/66116667-695be100-e5d3-11e9-8749-4db815aa6ce6.png)

We see a lot of the memberlist and serf reconnect messages, is that normal?

Here's my compose file:
```yml
portainer-agent:
    image: portainer/agent:1.4.0
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
      placement:
        constraints: [node.platform.os == linux]
  portainer:
    image: portainer/portainer:1.22.0
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify --admin-password '********'
    ports:
      - "9000:9000"
    volumes:
      - portainer_data2:/data
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 256M
      placement:
        constraints: [node.role == manager]
```
