### ISSUE TITLE
Support deployment in Swarm cluster with macvlan network

### ISSUE THREAD

**Issue by UniverseXXX** [portainer/agent#99]
Following up disscussions in #95 and https://github.com/portainer/portainer/issues/3279 re-openning this issue. @deviantony 

Since 1.5 realease portainer-agent won't run.

Here is my configurations:
Portainer:
```
  Portainer:
    image:          portainer/portainer
    container_name: Portainer
    hostname: Portainer
    domainname: mydomain
    restart:        always
    mac_address:  xx:xx:xx:xx:xx:xx
    networks:
      mynet:
        ipv4_address: 192.168.1.104
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.hostname == server
    command: --no-auth --admin-password=''
    volumes:
      - /Dockers/Portainer:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CAP_HOST_MANAGEMENT=true
```
Portainer-Agent:
```
  Portainer-Agent-FRW:
    image:          "portainer/agent:dev"
    container_name: Portainer-Agent-FRW
    hostname: Portainer-Agent-FRW
    domainname: mydomain
    restart:        always
    mac_address: xx:xx:xx:xx:xx:xx
    networks:
      mynet:
        ipv4_address: 192.168.1.134
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_CLUSTER_ADDR=192.168.1.134
      - CAP_HOST_MANAGEMENT=true
      - LOG_LEVEL=debug
```
